Check login - fixed password validation
stanislavfor/js-forms pull request #5
Opened 2018-06-13 22:07 UTC by stanislavfor

Юрий, здравствуйте! 
Исправил проверку пароля. Теперь проверка пороля проводится после проверки заполнения формы эл.почты. Отправил ветвь снова. Посмотрите, пожалуйста.

 (Комментарий к предыдущей правке: "@nobleworkshop requested changes on this pull request.
 Неплохо. Один момент. Одновременно происходит проверка и заполненности пароля и верности данных. Проверку на корректность данных надо делать только после того как удостоверились что данные введены. Незачем лишний раз дергать сервер, если пользователь не заполнил пароль.")

2018-06-15 21:04 UTC, nobleworkshop commented
@stanislavfor  Вот что я вижу если отправляю форму с пустым паролем: 
![image](https://user-images.githubusercontent.com/12967597/41489457-c66435f6-70f8-11e8-96d4-786d3116d787.png)

У вас также?

2018-06-15 21:04 UTC, nobleworkshop commented on js/login-form-check.js
> +											} else {
Что с отступами?

2018-06-15 21:06 UTC, nobleworkshop requested changes
Все также при пустом пароле отображает сразу 2 ошибки.

2018-06-21 19:33 UTC, stanislavfor commented
@nobleworkshop Переделал отступы в проверке имени и пароля. Делать вывод ошибок в js и уменьшить вложенность в эти уроки не успеваю по-времени, так как по необходимости пришлось доизучать работу с gitbush, чтобы не удалять ветви.

2018-06-22 21:14 UTC, nobleworkshop approved these changes
Сейчас все работает верно. В плане кода еще есть что улучшить. Двигаемся дальше!)

2018-07-04 21:13 UTC, merged