Check registration - Fixed name of attribute
stanislavfor/js-forms pull request #6
Opened 2018-06-13 22:25 UTC by stanislavfor

Отправляю ветвь с формой регистрации на проверку после правки атрибута в функции email. Юрий, посмотрите, пожалуйста.

(Предыдущий комментарий: Почему поле с паролем ищется по атрибуту name а поле с email нет?
var _inputPasswordName = $('[name="password"]');)

2018-06-15 21:10 UTC, nobleworkshop commented
@stanislavfor  А где изменения или ответ на вопрос?)

Сейчас все также:

```
var _inputEmailName = $('#inputEmailName');
...
var	_inputPasswordName = $('[name="password"]');
```

Вопрос к тому что стоит писать в одном стиле, и последовательно. Или выбрать оба по id. или оба по name="". Должна быть последовательность, и обоснованность решений. А сейчас получается, написали, заработало, ура!) А почему заработало, или почему подходы разные - не заморачиваемся. Не надо так.

2018-06-20 08:41 UTC, nobleworkshop requested changes
Нужны правки.

2018-06-21 02:35 UTC, stanislavfor commented
Здравствуйте, Юрий! Почему-то к предыдущему коммиту не исправиласт запись на гитхабе. То. что я делал по Вашим комментариям. Сейчас продолжаю правки. Внесу дополнительные изменения в файл и постараюсь отправить новым коммитом, без удаления ветвей. Спасибо за замечания.

2018-06-21 03:52 UTC, stanislavfor commented
Поправил значение переменной в mail.

2018-06-22 21:16 UTC, nobleworkshop approved these changes
Работает верно. Свою функцию скрипт выполняет. Двигаемся дальше.

2018-07-04 21:22 UTC, merged